# Generated by Django 5.0.4 on 2024-04-29 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('junction', models.CharField(max_length=100)),
                ('junction_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='M',
            fields=[
                ('id1', models.AutoField(primary_key=True, serialize=False)),
                ('s', models.CharField(max_length=100)),
                ('s2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.CharField(max_length=200)),
                ('green_on_url', models.CharField(max_length=200, null=True)),
                ('green_off_url', models.CharField(max_length=200, null=True)),
                ('red_switch_on_url', models.CharField(default='', max_length=200, null=True)),
                ('red_switch_off_url', models.CharField(default='', max_length=200, null=True)),
                ('junction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.junction')),
            ],
            options={
                'verbose_name_plural': 'Lanes',
            },
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_left_x', models.DecimalField(decimal_places=10, max_digits=20)),
                ('upper_left_y', models.DecimalField(decimal_places=10, max_digits=20)),
                ('upper_right_x', models.DecimalField(decimal_places=10, max_digits=20)),
                ('upper_right_y', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lower_left_x', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lower_left_y', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lower_right_x', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lower_right_y', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.lane')),
            ],
        ),
        migrations.CreateModel(
            name='OffSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offswitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.lane')),
                ('onswitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='OffTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offURL', models.CharField(max_length=500)),
                ('offtime', models.DateTimeField()),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.lane')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('district_code', models.CharField(max_length=100, unique=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.state')),
            ],
        ),
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taluka', models.CharField(max_length=100)),
                ('taluka_code', models.CharField(max_length=100, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.district')),
            ],
        ),
        migrations.AddField(
            model_name='junction',
            name='taluka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.taluka'),
        ),
    ]
